# Переименуйте этот файл в config.toml

# Режим "пробного запуска".
# true  - Утилита только покажет в логах, что она *собирается* сделать (обновить/удалить),
#         но не будет вносить реальных изменений в qBittorrent.
# false - Утилита будет выполнять реальные обновления и удаления.
dry_run = true

[qbit]
# Адрес вашего qBittorrent WebUI.
# Убедитесь, что WebUI включен в настройках qBittorrent.
url = "http://127.0.0.1:8080"

# Логин и пароль от WebUI qBittorrent
username = "admin"
password = "adminadmin"

[rutracker]
# Ваш сессионный cookie с Rutracker.
# (Инструкцию по получению см. в следующем разделе)
# Для запуска в режиме dry_run = true реальных обновлений не происходит и данное значение можно не вводить
bb_session_cookie = "СЮДА_ВСТАВИТЬ_СКОПИРОВАННОЕ_ЗНАЧЕНИЕ"